### PR TITLE
Fix for ROMs with custom media directory structure like EUI

### PR DESCRIPTION
**Pull request by zaoqi**

### CODE REVIEW

**Comment by zaoqi** [comment]
This module causes EUI5.9 to have no call ringtone that comes with the system,while https://github.com/Magisk-Modules-Repo/miui-10-sounds does not have this issue.

**Review by osm0sis — COMMENTED** [review]
That `rm -rf $target/media` line wouldn't affect the actual system during a Magisk module installation.. It would just clean the previous installation of the module. :confused:

**Comment by zaoqi** [comment]
How to fix it?

**Comment by osm0sis** [comment]
I don't have EMUI, so maybe you can tell me?

Did the above change fix it for you somehow? I was just struggling to see how it could make a difference.

**Comment by zaoqi** [comment]
I haven't tested above change.

Huawei EMUI != LeEco EUI

**Comment by osm0sis** [comment]
Ah. I see. So I reread your issue and my guess is it's because I fully replace the sounds folder with .replace. This is intentional. 

If you want to to just add ringtones then after install go and delete .replace from wherever in /data/adb/modules/nexusmedia/system/media and it'll work around that for you I think.

But anyway, I think this comes down to you just not realizing this module intentionally replaces all media with Nexus media, so there's nothing to fix.

Also, for future reference NEVER submit a pull request you haven't tested. You had no idea what you were changing.. :+1:

**Comment by zaoqi** [comment]
So I need to create a similar new module without this feature to fix this issue.

**Comment by osm0sis** [comment]
No just use it as intended or use the workaround I just explained to you. It's not hard.

**Comment by osm0sis** [comment]
I'll look into adding a "noreplace" mode for the module which can be activated by the /data/.nexusmedia special options. I'll keep you posted.

**Comment by osm0sis** [comment]
Here you go! https://github.com/Magisk-Modules-Repo/nexusmedia/commit/ee1d3b03e30164dab6161fcf384bebda330e980c

**Pull request closed without merging**
